# Generated by Django 4.2.1 on 2023-11-30 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=50, verbose_name='address line 1')),
                ('address_2', models.CharField(max_length=50, verbose_name='address line 2')),
                ('address_3', models.CharField(max_length=50, verbose_name='address line 3')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postcode', models.CharField(max_length=10, verbose_name='postcode')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
