# Generated by Django 4.2 on 2023-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('qty_in_stock', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
