# Generated by Django 4.2.1 on 2023-12-01 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=50, verbose_name='address line 1')),
                ('address_2', models.CharField(max_length=50, verbose_name='address line 2')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postcode', models.CharField(max_length=10, verbose_name='postcode')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('complete', models.BooleanField(default=False, verbose_name='completed')),
                ('txn_id', models.CharField(max_length=200, null=True, verbose_name='transaction id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer order',
                'verbose_name_plural': 'customer orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='product name')),
                ('price', models.FloatField(verbose_name='product price')),
                ('description', models.CharField(max_length=500, verbose_name='product description')),
                ('qty_in_stock', models.IntegerField(verbose_name='quantity in stock')),
                ('picture', models.ImageField(default='static/images/pic-not-found.jpg', upload_to='media/product_pictures/', verbose_name='product picture')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='last update date')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='order quantity')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='shop.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='shop.address')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=30, verbose_name='promotion name')),
                ('start', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('amount', models.FloatField(verbose_name='discount amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'product discount',
                'verbose_name_plural': 'product discounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='category name')),
                ('picture', models.ImageField(default='static/images/pic-not-found.jpg', upload_to='media/category_pictures/', verbose_name='category picture')),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
